<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AvalaraServiceTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        DB::table('avalara_service_types')->delete();
        $avalara_service_types = [
            ['id' => 1, 'service_type' => '6', 'avalara_transaction_types' => '19', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 1, 'minutes' => 0],
            ['id' => 2, 'service_type' => '8', 'avalara_transaction_types' => '19', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3, 'service_type' => '11', 'avalara_transaction_types' => '19', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 4, 'service_type' => '13', 'avalara_transaction_types' => '19', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 5, 'service_type' => '14', 'avalara_transaction_types' => '19', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 6, 'service_type' => '30', 'avalara_transaction_types' => '19', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 7, 'service_type' => '37', 'avalara_transaction_types' => '19', 'service_type_name' => 'Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 8, 'service_type' => '48', 'avalara_transaction_types' => '19', 'service_type_name' => 'Wireless Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 9, 'service_type' => '53', 'avalara_transaction_types' => '19', 'service_type_name' => 'LNP (Local Number Portability)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 10, 'service_type' => '577', 'avalara_transaction_types' => '19', 'service_type_name' => 'Enhanced Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 11, 'service_type' => '596', 'avalara_transaction_types' => '19', 'service_type_name' => 'Access-Local Only Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 12, 'service_type' => '635', 'avalara_transaction_types' => '19', 'service_type_name' => 'Toll-Free Number', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 13, 'service_type' => '21', 'avalara_transaction_types' => '19', 'service_type_name' => 'Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 14, 'service_type' => '578', 'avalara_transaction_types' => '19', 'service_type_name' => 'PBX', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 15, 'service_type' => '566', 'avalara_transaction_types' => '19', 'service_type_name' => 'PBX Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 16, 'service_type' => '41', 'avalara_transaction_types' => '19', 'service_type_name' => 'PBX Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 17, 'service_type' => '579', 'avalara_transaction_types' => '19', 'service_type_name' => 'PBX High Capacity', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 18, 'service_type' => '582', 'avalara_transaction_types' => '19', 'service_type_name' => 'High Capacity Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 19, 'service_type' => '580', 'avalara_transaction_types' => '19', 'service_type_name' => 'High Capacity Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 20, 'service_type' => '52', 'avalara_transaction_types' => '19', 'service_type_name' => 'Wireless Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 21, 'service_type' => '43', 'avalara_transaction_types' => '19', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 45, 'service_type' => '49', 'avalara_transaction_types' => '19', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 47, 'service_type' => '50', 'avalara_transaction_types' => '19', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 48, 'service_type' => '51', 'avalara_transaction_types' => '19', 'service_type_name' => 'International Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 22, 'service_type' => '48', 'avalara_transaction_types' => '20', 'service_type_name' => 'Wireless Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 23, 'service_type' => '52', 'avalara_transaction_types' => '20', 'service_type_name' => 'Wireless Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 24, 'service_type' => '43', 'avalara_transaction_types' => '20', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 35, 'service_type' => '6', 'avalara_transaction_types' => '20', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 1, 'minutes' => 0],
            ['id' => 36, 'service_type' => '8', 'avalara_transaction_types' => '20', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 37, 'service_type' => '11', 'avalara_transaction_types' => '20', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 38, 'service_type' => '13', 'avalara_transaction_types' => '20', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 39, 'service_type' => '14', 'avalara_transaction_types' => '20', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 40, 'service_type' => '21', 'avalara_transaction_types' => '20', 'service_type_name' => 'Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 41, 'service_type' => '30', 'avalara_transaction_types' => '20', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 42, 'service_type' => '37', 'avalara_transaction_types' => '20', 'service_type_name' => 'Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 43, 'service_type' => '41', 'avalara_transaction_types' => '20', 'service_type_name' => 'PBX Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 44, 'service_type' => '48', 'avalara_transaction_types' => '20', 'service_type_name' => 'Wireless Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 46, 'service_type' => '49', 'avalara_transaction_types' => '20', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 49, 'service_type' => '50', 'avalara_transaction_types' => '20', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 50, 'service_type' => '51', 'avalara_transaction_types' => '20', 'service_type_name' => 'International Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 51, 'service_type' => '52', 'avalara_transaction_types' => '20', 'service_type_name' => 'Wireless Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 52, 'service_type' => '53', 'avalara_transaction_types' => '20', 'service_type_name' => 'LNP (Local Number Portability)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 53, 'service_type' => '566', 'avalara_transaction_types' => '20', 'service_type_name' => 'PBX Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 54, 'service_type' => '577', 'avalara_transaction_types' => '20', 'service_type_name' => 'Enhanced Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 55, 'service_type' => '578', 'avalara_transaction_types' => '20', 'service_type_name' => 'PBX', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 56, 'service_type' => '579', 'avalara_transaction_types' => '20', 'service_type_name' => 'PBX High Capacity', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 57, 'service_type' => '580', 'avalara_transaction_types' => '20', 'service_type_name' => 'High Capacity Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 59, 'service_type' => '582', 'avalara_transaction_types' => '20', 'service_type_name' => 'High Capacity Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 60, 'service_type' => '596', 'avalara_transaction_types' => '20', 'service_type_name' => 'Access-Local Only Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 61, 'service_type' => '635', 'avalara_transaction_types' => '20', 'service_type_name' => 'Toll-Free Number', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 25, 'service_type' => '43', 'avalara_transaction_types' => '59', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 62, 'service_type' => '48', 'avalara_transaction_types' => '59', 'service_type_name' => 'Wireless Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 63, 'service_type' => '52', 'avalara_transaction_types' => '59', 'service_type_name' => 'Wireless Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 64, 'service_type' => '6', 'avalara_transaction_types' => '59', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 1, 'minutes' => 0],
            ['id' => 65, 'service_type' => '8', 'avalara_transaction_types' => '59', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 66, 'service_type' => '11', 'avalara_transaction_types' => '59', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 67, 'service_type' => '13', 'avalara_transaction_types' => '59', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 68, 'service_type' => '14', 'avalara_transaction_types' => '59', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 69, 'service_type' => '21', 'avalara_transaction_types' => '59', 'service_type_name' => 'Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 70, 'service_type' => '30', 'avalara_transaction_types' => '59', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 71, 'service_type' => '37', 'avalara_transaction_types' => '59', 'service_type_name' => 'Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 72, 'service_type' => '41', 'avalara_transaction_types' => '59', 'service_type_name' => 'PBX Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 73, 'service_type' => '48', 'avalara_transaction_types' => '59', 'service_type_name' => 'Wireless Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 74, 'service_type' => '49', 'avalara_transaction_types' => '59', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 75, 'service_type' => '50', 'avalara_transaction_types' => '59', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 76, 'service_type' => '51', 'avalara_transaction_types' => '59', 'service_type_name' => 'International Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 77, 'service_type' => '52', 'avalara_transaction_types' => '59', 'service_type_name' => 'Wireless Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 78, 'service_type' => '53', 'avalara_transaction_types' => '59', 'service_type_name' => 'LNP (Local Number Portability)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 79, 'service_type' => '566', 'avalara_transaction_types' => '59', 'service_type_name' => 'PBX Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 80, 'service_type' => '577', 'avalara_transaction_types' => '59', 'service_type_name' => 'Enhanced Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 81, 'service_type' => '578', 'avalara_transaction_types' => '59', 'service_type_name' => 'PBX', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 82, 'service_type' => '579', 'avalara_transaction_types' => '59', 'service_type_name' => 'PBX High Capacity', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 83, 'service_type' => '580', 'avalara_transaction_types' => '59', 'service_type_name' => 'High Capacity Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 84, 'service_type' => '582', 'avalara_transaction_types' => '59', 'service_type_name' => 'High Capacity Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 85, 'service_type' => '596', 'avalara_transaction_types' => '59', 'service_type_name' => 'Access-Local Only Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 86, 'service_type' => '635', 'avalara_transaction_types' => '59', 'service_type_name' => 'Toll-Free Number', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 26, 'service_type' => '6', 'avalara_transaction_types' => '65', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 27, 'service_type' => '11', 'avalara_transaction_types' => '65', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 28, 'service_type' => '14', 'avalara_transaction_types' => '65', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 29, 'service_type' => '30', 'avalara_transaction_types' => '65', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 30, 'service_type' => '49', 'avalara_transaction_types' => '65', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 31, 'service_type' => '50', 'avalara_transaction_types' => '65', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 32, 'service_type' => '51', 'avalara_transaction_types' => '65', 'service_type_name' => 'International Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 33, 'service_type' => '577', 'avalara_transaction_types' => '65', 'service_type_name' => 'Enhanced Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 34, 'service_type' => '43', 'avalara_transaction_types' => '65', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 87, 'service_type' => '0', 'avalara_transaction_types' => '0', 'service_type_name' => 'No Tax', 'taxable_amount' => 1, 'lines' => 1, 'minutes' => 1],

            ['id' => 88, 'service_type' => '1', 'avalara_transaction_types' => '1', 'service_type_name' => 'Toll', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 89, 'service_type' => '2', 'avalara_transaction_types' => '1', 'service_type_name' => 'Toll-Free', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 90, 'service_type' => '3', 'avalara_transaction_types' => '1', 'service_type_name' => 'WATS', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 91, 'service_type' => '4', 'avalara_transaction_types' => '1', 'service_type_name' => 'Private Line', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 92, 'service_type' => '12', 'avalara_transaction_types' => '1', 'service_type_name' => 'International Toll', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 93, 'service_type' => '14', 'avalara_transaction_types' => '1', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 94, 'service_type' => '16', 'avalara_transaction_types' => '1', 'service_type_name' => '900', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 95, 'service_type' => '27', 'avalara_transaction_types' => '1', 'service_type_name' => 'Data', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 96, 'service_type' => '54', 'avalara_transaction_types' => '1', 'service_type_name' => 'Directory Assistance', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 97, 'service_type' => '562', 'avalara_transaction_types' => '1', 'service_type_name' => 'Local Loop', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 98, 'service_type' => '635', 'avalara_transaction_types' => '1', 'service_type_name' => 'Toll Free Number', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 99, 'service_type' => '1', 'avalara_transaction_types' => '2', 'service_type_name' => 'Toll', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 100, 'service_type' => '2', 'avalara_transaction_types' => '2', 'service_type_name' => 'Toll-Free', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 101, 'service_type' => '3', 'avalara_transaction_types' => '2', 'service_type_name' => 'WATS', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 102, 'service_type' => '4', 'avalara_transaction_types' => '2', 'service_type_name' => 'Private Line', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 103, 'service_type' => '12', 'avalara_transaction_types' => '2', 'service_type_name' => 'International Toll', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 104, 'service_type' => '14', 'avalara_transaction_types' => '2', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 105, 'service_type' => '16', 'avalara_transaction_types' => '2', 'service_type_name' => '900', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 106, 'service_type' => '27', 'avalara_transaction_types' => '2', 'service_type_name' => 'Data', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 107, 'service_type' => '54', 'avalara_transaction_types' => '2', 'service_type_name' => 'Directory Assistance', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 108, 'service_type' => '630', 'avalara_transaction_types' => '2', 'service_type_name' => 'Private Line (10% Rule)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 109, 'service_type' => '631', 'avalara_transaction_types' => '2', 'service_type_name' => 'Data (10% Rule)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 110, 'service_type' => '635', 'avalara_transaction_types' => '2', 'service_type_name' => 'Toll Free Number', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 111, 'service_type' => '6', 'avalara_transaction_types' => '3', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 112, 'service_type' => '6', 'avalara_transaction_types' => '3', 'service_type_name' => 'Local Loop', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 113, 'service_type' => '9', 'avalara_transaction_types' => '3', 'service_type_name' => 'Directory Ads', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 114, 'service_type' => '14', 'avalara_transaction_types' => '3', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 115, 'service_type' => '34', 'avalara_transaction_types' => '3', 'service_type_name' => 'Conference Bridge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 116, 'service_type' => '37', 'avalara_transaction_types' => '3', 'service_type_name' => 'Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 117, 'service_type' => '38', 'avalara_transaction_types' => '3', 'service_type_name' => 'Wire Maintenance Plan', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 118, 'service_type' => '46', 'avalara_transaction_types' => '3', 'service_type_name' => 'PICC', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 119, 'service_type' => '47', 'avalara_transaction_types' => '3', 'service_type_name' => 'No Pick PICC', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 120, 'service_type' => '57', 'avalara_transaction_types' => '3', 'service_type_name' => 'Data Processing', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 121, 'service_type' => '96', 'avalara_transaction_types' => '3', 'service_type_name' => 'No Pick PICC Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 122, 'service_type' => '97', 'avalara_transaction_types' => '3', 'service_type_name' => 'PICC Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 123, 'service_type' => '414', 'avalara_transaction_types' => '3', 'service_type_name' => 'Printing Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 124, 'service_type' => '415', 'avalara_transaction_types' => '3', 'service_type_name' => 'Copying Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 125, 'service_type' => '416', 'avalara_transaction_types' => '3', 'service_type_name' => 'Credit Card Processing Fee-Part of Sale', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 126, 'service_type' => '417', 'avalara_transaction_types' => '3', 'service_type_name' => 'Credit Card Processing Fee-Separate Sale', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 127, 'service_type' => '420', 'avalara_transaction_types' => '3', 'service_type_name' => 'Protection & Security Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 128, 'service_type' => '434', 'avalara_transaction_types' => '3', 'service_type_name' => 'Advertising', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 129, 'service_type' => '439', 'avalara_transaction_types' => '3', 'service_type_name' => 'Background Music Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 130, 'service_type' => '447', 'avalara_transaction_types' => '3', 'service_type_name' => 'Telephone Answering Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 131, 'service_type' => '570', 'avalara_transaction_types' => '3', 'service_type_name' => 'Directory Listing', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 132, 'service_type' => '575', 'avalara_transaction_types' => '3', 'service_type_name' => 'Conference Bridge-Intrastate', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 133, 'service_type' => '576', 'avalara_transaction_types' => '3', 'service_type_name' => 'Conference Bridge-Intrastate w Dial In', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 134, 'service_type' => '589', 'avalara_transaction_types' => '3', 'service_type_name' => 'Conference Bridge-Interstate', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 135, 'service_type' => '593', 'avalara_transaction_types' => '3', 'service_type_name' => 'Info Svcs-Private Physical Trans', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 136, 'service_type' => '594', 'avalara_transaction_types' => '3', 'service_type_name' => 'Info Svcs-Private Electronic Trans', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 137, 'service_type' => '597', 'avalara_transaction_types' => '3', 'service_type_name' => 'Info Svcs-Public Electronic Trans', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 138, 'service_type' => '598', 'avalara_transaction_types' => '3', 'service_type_name' => 'Info Svcs-Public Physical Trans', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 139, 'service_type' => '599', 'avalara_transaction_types' => '3', 'service_type_name' => 'E-mail Hosting Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 140, 'service_type' => '600', 'avalara_transaction_types' => '3', 'service_type_name' => 'Real Property Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 141, 'service_type' => '602', 'avalara_transaction_types' => '3', 'service_type_name' => 'Services-Professional', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 142, 'service_type' => '603', 'avalara_transaction_types' => '3', 'service_type_name' => 'Online Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 143, 'service_type' => '608', 'avalara_transaction_types' => '3', 'service_type_name' => 'Conference Bridge Interstate w Dial In', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 144, 'service_type' => '614', 'avalara_transaction_types' => '3', 'service_type_name' => 'Telecom Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 145, 'service_type' => '632', 'avalara_transaction_types' => '3', 'service_type_name' => 'Service Contracts', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 146, 'service_type' => '638', 'avalara_transaction_types' => '3', 'service_type_name' => 'Security Monitoring Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 147, 'service_type' => '639', 'avalara_transaction_types' => '3', 'service_type_name' => 'Streaming Internet Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 148, 'service_type' => '644', 'avalara_transaction_types' => '3', 'service_type_name' => 'Info Svcs-Pub Elec Trans (Fin & Securities)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 149, 'service_type' => '687', 'avalara_transaction_types' => '3', 'service_type_name' => 'Admissions', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 150, 'service_type' => '7', 'avalara_transaction_types' => '4', 'service_type_name' => 'Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 151, 'service_type' => '8', 'avalara_transaction_types' => '4', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 152, 'service_type' => '11', 'avalara_transaction_types' => '4', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 153, 'service_type' => '14', 'avalara_transaction_types' => '4', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 154, 'service_type' => '6', 'avalara_transaction_types' => '5', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 155, 'service_type' => '7', 'avalara_transaction_types' => '5', 'service_type_name' => 'Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 156, 'service_type' => '8', 'avalara_transaction_types' => '5', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 157, 'service_type' => '10', 'avalara_transaction_types' => '5', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 158, 'service_type' => '11', 'avalara_transaction_types' => '5', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 159, 'service_type' => '29', 'avalara_transaction_types' => '5', 'service_type_name' => 'Web Hosting', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 160, 'service_type' => '58', 'avalara_transaction_types' => '5', 'service_type_name' => 'Access Line', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 161, 'service_type' => '6', 'avalara_transaction_types' => '6', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 162, 'service_type' => '10', 'avalara_transaction_types' => '6', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 163, 'service_type' => '11', 'avalara_transaction_types' => '6', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 164, 'service_type' => '13', 'avalara_transaction_types' => '6', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 165, 'service_type' => '4', 'avalara_transaction_types' => '7', 'service_type_name' => 'Private Line', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 166, 'service_type' => '5', 'avalara_transaction_types' => '7', 'service_type_name' => 'Local Exchange Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 167, 'service_type' => '14', 'avalara_transaction_types' => '7', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 168, 'service_type' => '20', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Fee', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 169, 'service_type' => '20', 'avalara_transaction_types' => '7', 'service_type_name' => 'Number Portability Recovery', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 170, 'service_type' => '21', 'avalara_transaction_types' => '7', 'service_type_name' => 'Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 171, 'service_type' => '24', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX/Trunk', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 172, 'service_type' => '27', 'avalara_transaction_types' => '7', 'service_type_name' => 'Data', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 173, 'service_type' => '30', 'avalara_transaction_types' => '7', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 174, 'service_type' => '40', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex / DID Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 175, 'service_type' => '41', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 176, 'service_type' => '42', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex Trunk', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 177, 'service_type' => '43', 'avalara_transaction_types' => '7', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 178, 'service_type' => '45', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Trunk', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

            ['id' => 179, 'service_type' => '84', 'avalara_transaction_types' => '7', 'service_type_name' => 'Late Charge Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 180, 'service_type' => '85', 'avalara_transaction_types' => '7', 'service_type_name' => 'Local Exchange Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 181, 'service_type' => '86', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Fee Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 182, 'service_type' => '86', 'avalara_transaction_types' => '7', 'service_type_name' => 'Number Portability Recovery Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 183, 'service_type' => '87', 'avalara_transaction_types' => '7', 'service_type_name' => 'Lines Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 184, 'service_type' => '89', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX Trunk Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

            ['id' => 185, 'service_type' => '90', 'avalara_transaction_types' => '7', 'service_type_name' => 'Local Feature Charge Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 186, 'service_type' => '91', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex Extension Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 187, 'service_type' => '92', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX Extension Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 188, 'service_type' => '93', 'avalara_transaction_types' => '7', 'service_type_name' => 'Invoice Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 189, 'service_type' => '94', 'avalara_transaction_types' => '7', 'service_type_name' => 'Lines Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 190, 'service_type' => '95', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Trunk Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

            ['id' => 191, 'service_type' => '566', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 192, 'service_type' => '567', 'avalara_transaction_types' => '7', 'service_type_name' => 'PBX Outbound Channel Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 193, 'service_type' => '580', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Extension', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 194, 'service_type' => '581', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Extension Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 195, 'service_type' => '582', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 196, 'service_type' => '583', 'avalara_transaction_types' => '7', 'service_type_name' => 'High Capacity Outbound Channel Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 197, 'service_type' => '587', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex Outbound Channel', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 198, 'service_type' => '588', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex Outbound Channel Bundle', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

            ['id' => 199, 'service_type' => '612', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Charge Multi-line', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 200, 'service_type' => '613', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Charge Multi-line Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 201, 'service_type' => '623', 'avalara_transaction_types' => '7', 'service_type_name' => 'Centrex Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 202, 'service_type' => '625', 'avalara_transaction_types' => '7', 'service_type_name' => 'Customer Premise Equip Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 203, 'service_type' => '641', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Charge Centrex', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 204, 'service_type' => '642', 'avalara_transaction_types' => '7', 'service_type_name' => 'FCC Subscriber Line Charge Centrex Bundle', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 205, 'service_type' => '10', 'avalara_transaction_types' => '8', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 206, 'service_type' => '6', 'avalara_transaction_types' => '9', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 207, 'service_type' => '10', 'avalara_transaction_types' => '9', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 208, 'service_type' => '11', 'avalara_transaction_types' => '9', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 209, 'service_type' => '14', 'avalara_transaction_types' => '9', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 210, 'service_type' => '15', 'avalara_transaction_types' => '10', 'service_type_name' => 'Product', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 211, 'service_type' => '31', 'avalara_transaction_types' => '10', 'service_type_name' => 'Use', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 212, 'service_type' => '32', 'avalara_transaction_types' => '10', 'service_type_name' => 'Debit', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 213, 'service_type' => '63', 'avalara_transaction_types' => '10', 'service_type_name' => 'Restocking Fee - Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 214, 'service_type' => '64', 'avalara_transaction_types' => '10', 'service_type_name' => 'Restocking Fee – Purchase', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 215, 'service_type' => '65', 'avalara_transaction_types' => '10', 'service_type_name' => 'Partial Credit', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 216, 'service_type' => '103', 'avalara_transaction_types' => '10', 'service_type_name' => 'Sales Tax and FUSF', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 217, 'service_type' => '174', 'avalara_transaction_types' => '10', 'service_type_name' => 'Monitors Less Than 4 Inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 218, 'service_type' => '175', 'avalara_transaction_types' => '10', 'service_type_name' => 'Monitors Between 5-14 inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 219, 'service_type' => '177', 'avalara_transaction_types' => '10', 'service_type_name' => 'Monitors Greater Than 35 Inches.', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 220, 'service_type' => '230', 'avalara_transaction_types' => '10', 'service_type_name' => 'Coupon Books', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 221, 'service_type' => '232', 'avalara_transaction_types' => '10', 'service_type_name' => 'Non-Lead Based Batteries', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 222, 'service_type' => '565', 'avalara_transaction_types' => '10', 'service_type_name' => 'Debit-Wireless', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 223, 'service_type' => '568', 'avalara_transaction_types' => '10', 'service_type_name' => 'Central Office Equipment-Sales', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 224, 'service_type' => '569', 'avalara_transaction_types' => '10', 'service_type_name' => 'Central Office Equipment-Use', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 225, 'service_type' => '570', 'avalara_transaction_types' => '10', 'service_type_name' => 'Fixture', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 226, 'service_type' => '643', 'avalara_transaction_types' => '10', 'service_type_name' => 'Coupon Books', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 227, 'service_type' => '655', 'avalara_transaction_types' => '10', 'service_type_name' => 'Non-Lead Based Batteries', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 228, 'service_type' => '688', 'avalara_transaction_types' => '10', 'service_type_name' => 'Roadside Assistance', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 229, 'service_type' => '689', 'avalara_transaction_types' => '10', 'service_type_name' => 'Equipment Insurance Coverage - Mandatory', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 230, 'service_type' => '691', 'avalara_transaction_types' => '10', 'service_type_name' => 'Equipment Insurance Coverage - Optional', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 231, 'service_type' => '692', 'avalara_transaction_types' => '10', 'service_type_name' => 'Equipment Extended Warranty - Mandatory', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 232, 'service_type' => '693', 'avalara_transaction_types' => '10', 'service_type_name' => 'Equipment Extended Warranty - Optional', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 233, 'service_type' => '709', 'avalara_transaction_types' => '10', 'service_type_name' => 'Monitors Between 15-34 inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 234, 'service_type' => '755', 'avalara_transaction_types' => '10', 'service_type_name' => 'Books-Educational-College & Trade School', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 235, 'service_type' => '756', 'avalara_transaction_types' => '10', 'service_type_name' => 'Magazine Subscription-Annually-Delivered by US Mail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 236, 'service_type' => '757', 'avalara_transaction_types' => '10', 'service_type_name' => 'Magazine Subscription-Quarterly-Delivered by US Mail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 237, 'service_type' => '762', 'avalara_transaction_types' => '10', 'service_type_name' => 'Repair Parts', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 238, 'service_type' => '17', 'avalara_transaction_types' => '11', 'service_type_name' => 'FOB Origin', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 239, 'service_type' => '18', 'avalara_transaction_types' => '11', 'service_type_name' => 'FOB Destination', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 240, 'service_type' => '6', 'avalara_transaction_types' => '13', 'service_type_name' => 'Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 241, 'service_type' => '10', 'avalara_transaction_types' => '13', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 242, 'service_type' => '11', 'avalara_transaction_types' => '13', 'service_type_name' => 'Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 243, 'service_type' => '14', 'avalara_transaction_types' => '13', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 244, 'service_type' => '30', 'avalara_transaction_types' => '13', 'service_type_name' => 'Local Feature Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 245, 'service_type' => '33', 'avalara_transaction_types' => '13', 'service_type_name' => 'Roaming Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 246, 'service_type' => '43', 'avalara_transaction_types' => '13', 'service_type_name' => 'Invoice', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 247, 'service_type' => '49', 'avalara_transaction_types' => '13', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 248, 'service_type' => '50', 'avalara_transaction_types' => '13', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 249, 'service_type' => '51', 'avalara_transaction_types' => '13', 'service_type_name' => 'International Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 250, 'service_type' => '98', 'avalara_transaction_types' => '13', 'service_type_name' => 'Access Number', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 251, 'service_type' => '99', 'avalara_transaction_types' => '13', 'service_type_name' => 'Interstate Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 252, 'service_type' => '100', 'avalara_transaction_types' => '13', 'service_type_name' => 'Intrastate Access Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 253, 'service_type' => '101', 'avalara_transaction_types' => '13', 'service_type_name' => 'Interstate Roaming', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 254, 'service_type' => '102', 'avalara_transaction_types' => '13', 'service_type_name' => 'Intrastate Roaming', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 255, 'service_type' => '572', 'avalara_transaction_types' => '13', 'service_type_name' => 'Digital Download', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 256, 'service_type' => '577', 'avalara_transaction_types' => '13', 'service_type_name' => 'Enhanced Features', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 2550, 'service_type' => '591', 'avalara_transaction_types' => '13', 'service_type_name' => 'Access Number-No Contract', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 2560, 'service_type' => '592', 'avalara_transaction_types' => '13', 'service_type_name' => 'Enhanced Features', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

            ['id' => 257, 'service_type' => '610', 'avalara_transaction_types' => '13', 'service_type_name' => 'Early Termination Fees', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 258, 'service_type' => '622', 'avalara_transaction_types' => '13', 'service_type_name' => 'Text Message', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 352, 'service_type' => '15', 'avalara_transaction_types' => '14', 'service_type_name' => 'Product', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 353, 'service_type' => '636', 'avalara_transaction_types' => '14', 'service_type_name' => 'Remotely Accessed Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 354, 'service_type' => '658', 'avalara_transaction_types' => '14', 'service_type_name' => 'Product - India Interstate Supply', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 355, 'service_type' => '659', 'avalara_transaction_types' => '14', 'service_type_name' => 'Product - India Intrastate Supply', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 356, 'service_type' => '676', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Downloaded Audio', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 357, 'service_type' => '677', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Streaming Audio', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 358, 'service_type' => '678', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Downloaded Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 359, 'service_type' => '679', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Streaming Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 360, 'service_type' => '680', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Downloaded Video Game', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 361, 'service_type' => '681', 'avalara_transaction_types' => '14', 'service_type_name' => 'Digital Streaming Video Game', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 362, 'service_type' => '682', 'avalara_transaction_types' => '14', 'service_type_name' => 'Downloaded Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 259, 'service_type' => '6', 'avalara_transaction_types' => '16', 'service_type_name' => 'Access Charge (Alias Basic Service)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 260, 'service_type' => '8', 'avalara_transaction_types' => '16', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 261, 'service_type' => '13', 'avalara_transaction_types' => '16', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 262, 'service_type' => '14', 'avalara_transaction_types' => '16', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 263, 'service_type' => '35', 'avalara_transaction_types' => '16', 'service_type_name' => 'Premium Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 264, 'service_type' => '36', 'avalara_transaction_types' => '16', 'service_type_name' => 'Pay Per View Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 265, 'service_type' => '37', 'avalara_transaction_types' => '16', 'service_type_name' => 'Equipment Rental', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 266, 'service_type' => '39', 'avalara_transaction_types' => '16', 'service_type_name' => 'TV Guide', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 267, 'service_type' => '584', 'avalara_transaction_types' => '16', 'service_type_name' => 'Digital Channel Tier', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 268, 'service_type' => '610', 'avalara_transaction_types' => '16', 'service_type_name' => 'Early Termination Fees', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 269, 'service_type' => '615', 'avalara_transaction_types' => '16', 'service_type_name' => 'Equipment Sales', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 270, 'service_type' => '654', 'avalara_transaction_types' => '16', 'service_type_name' => 'Equipment Rental Basic ', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 271, 'service_type' => '6', 'avalara_transaction_types' => '18', 'service_type_name' => 'Access Charge (Alias Basic Service)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 272, 'service_type' => '8', 'avalara_transaction_types' => '18', 'service_type_name' => 'Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 273, 'service_type' => '13', 'avalara_transaction_types' => '18', 'service_type_name' => 'Equipment Repair', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 274, 'service_type' => '14', 'avalara_transaction_types' => '18', 'service_type_name' => 'Late Charge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 275, 'service_type' => '35', 'avalara_transaction_types' => '18', 'service_type_name' => 'Premium Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 276, 'service_type' => '36', 'avalara_transaction_types' => '18', 'service_type_name' => 'Pay Per View Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 277, 'service_type' => '37', 'avalara_transaction_types' => '18', 'service_type_name' => 'Equipment Rentale', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 278, 'service_type' => '39', 'avalara_transaction_types' => '18', 'service_type_name' => 'TV Guide', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 279, 'service_type' => '21', 'avalara_transaction_types' => '21', 'service_type_name' => 'Lines', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],
            ['id' => 280, 'service_type' => '49', 'avalara_transaction_types' => '21', 'service_type_name' => 'Interstate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 281, 'service_type' => '50', 'avalara_transaction_types' => '21', 'service_type_name' => 'Intrastate Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 282, 'service_type' => '55', 'avalara_transaction_types' => '21', 'service_type_name' => 'Local Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 283, 'service_type' => '56', 'avalara_transaction_types' => '21', 'service_type_name' => 'Provisioning', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 284, 'service_type' => '59', 'avalara_transaction_types' => '24', 'service_type_name' => 'Licensed Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 285, 'service_type' => '60', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maintenance Agreement', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 286, 'service_type' => '60', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maintenance Agreement-Mandatory-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 287, 'service_type' => '61', 'avalara_transaction_types' => '24', 'service_type_name' => 'Report on CD or Paper Form', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 288, 'service_type' => '595', 'avalara_transaction_types' => '24', 'service_type_name' => 'Downloaded Licensed Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 289, 'service_type' => '636', 'avalara_transaction_types' => '24', 'service_type_name' => 'Remotely Accessed Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 290, 'service_type' => '663', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Set Up-Optional-Remotely Accessed', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 291, 'service_type' => '666', 'avalara_transaction_types' => '24', 'service_type_name' => 'Computer Consulting-Optional-Remotely Access', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 292, 'service_type' => '667', 'avalara_transaction_types' => '24', 'service_type_name' => 'Computer Training-Optional-Remotely Accessed', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 293, 'service_type' => '668', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Setup-Mandatory-Remotely Accessed', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 294, 'service_type' => '669', 'avalara_transaction_types' => '24', 'service_type_name' => 'Computer Consulting-Mandatory-Remotely Accessed', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 295, 'service_type' => '670', 'avalara_transaction_types' => '24', 'service_type_name' => 'Computer Training-Mandatory-Remotely Accessed', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 296, 'service_type' => '671', 'avalara_transaction_types' => '24', 'service_type_name' => 'Modification Charges-Remotely Accessed Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 297, 'service_type' => '694', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maintenance Agreement-Optional-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 298, 'service_type' => '695', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maintenance Agreement-Mandatory-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 299, 'service_type' => '696', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maintenance Agreement-Optional-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 300, 'service_type' => '699', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Mandatory-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 301, 'service_type' => '700', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Mandatory-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 302, 'service_type' => '702', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Mandatory-Remote Access', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 303, 'service_type' => '703', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Optional-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 304, 'service_type' => '704', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Mandatory-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 305, 'service_type' => '705', 'avalara_transaction_types' => '24', 'service_type_name' => 'Software Maint Agreement-Optional-Remote Access', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 306, 'service_type' => '707', 'avalara_transaction_types' => '24', 'service_type_name' => 'Licensed Load and Leave Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 307, 'service_type' => '715', 'avalara_transaction_types' => '24', 'service_type_name' => 'Canned Computer Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 308, 'service_type' => '716', 'avalara_transaction_types' => '24', 'service_type_name' => 'Modification Charges', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 309, 'service_type' => '717', 'avalara_transaction_types' => '24', 'service_type_name' => 'Modified Computer Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 310, 'service_type' => '718', 'avalara_transaction_types' => '24', 'service_type_name' => 'Custom Computer Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 311, 'service_type' => '719', 'avalara_transaction_types' => '24', 'service_type_name' => 'Canned Load and Leave Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3070, 'service_type' => '720', 'avalara_transaction_types' => '24', 'service_type_name' => 'Custom Load and Leave Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3080, 'service_type' => '721', 'avalara_transaction_types' => '24', 'service_type_name' => 'Modified Load and Leave Software', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3090, 'service_type' => '722', 'avalara_transaction_types' => '24', 'service_type_name' => 'Canned Software Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3100, 'service_type' => '723', 'avalara_transaction_types' => '24', 'service_type_name' => 'Modified Software Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 3110, 'service_type' => '724', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Optional-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 312, 'service_type' => '725', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Optional-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 313, 'service_type' => '726', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Optional-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 314, 'service_type' => '727', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Optional-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 315, 'service_type' => '728', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Optional-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 316, 'service_type' => '729', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Mandatory-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 317, 'service_type' => '730', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Mandatory-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 318, 'service_type' => '731', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Mandatory-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 319, 'service_type' => '732', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Mandatory-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 320, 'service_type' => '733', 'avalara_transaction_types' => '24', 'service_type_name' => 'Set Up-Mandatory-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 321, 'service_type' => '734', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Optional-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 322, 'service_type' => '735', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Mandatory-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 323, 'service_type' => '736', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Optional-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 324, 'service_type' => '737', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Mandatory-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 325, 'service_type' => '738', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Optional-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 326, 'service_type' => '739', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Mandatory-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 327, 'service_type' => '740', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Optional-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 328, 'service_type' => '741', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Mandatory-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 329, 'service_type' => '742', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Optional-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 330, 'service_type' => '743', 'avalara_transaction_types' => '24', 'service_type_name' => 'Consulting-Mandatory-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 331, 'service_type' => '744', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Optional-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 332, 'service_type' => '745', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Mandatory-Canned', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 333, 'service_type' => '746', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Optional-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 334, 'service_type' => '747', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Mandatory-Custom', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 335, 'service_type' => '748', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Optional-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 336, 'service_type' => '749', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Mandatory-Downloaded', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 337, 'service_type' => '750', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Optional-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 338, 'service_type' => '751', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Mandatory-Load and Leave', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 339, 'service_type' => '752', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Optional-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 340, 'service_type' => '753', 'avalara_transaction_types' => '24', 'service_type_name' => 'Training-Mandatory-Modified', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 341, 'service_type' => '62', 'avalara_transaction_types' => '25', 'service_type_name' => 'Information Retrieval', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 342, 'service_type' => '646', 'avalara_transaction_types' => '25', 'service_type_name' => 'Information Retrieval (Provider Data)', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 343, 'service_type' => '660', 'avalara_transaction_types' => '25', 'service_type_name' => 'No Retrieval-Disaster Recovery', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 344, 'service_type' => '706', 'avalara_transaction_types' => '25', 'service_type_name' => 'Off - Site Use of CPU', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 345, 'service_type' => '754', 'avalara_transaction_types' => '25', 'service_type_name' => 'Processor Located out of State', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 346, 'service_type' => '7', 'avalara_transaction_types' => '15', 'service_type_name' => 'Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 347, 'service_type' => '624', 'avalara_transaction_types' => '15', 'service_type_name' => 'Wireless Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 348, 'service_type' => '627', 'avalara_transaction_types' => '15', 'service_type_name' => 'Internet Access', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 349, 'service_type' => '629', 'avalara_transaction_types' => '15', 'service_type_name' => 'Messaging Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 350, 'service_type' => '656', 'avalara_transaction_types' => '15', 'service_type_name' => 'Service - India Interstate Supply', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 351, 'service_type' => '657', 'avalara_transaction_types' => '15', 'service_type_name' => 'Service - India Intrastate Supply', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 363, 'service_type' => '106', 'avalara_transaction_types' => '32', 'service_type_name' => 'General Rule', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 364, 'service_type' => '174', 'avalara_transaction_types' => '32', 'service_type_name' => 'Monitors Less Than 4 Inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 365, 'service_type' => '175', 'avalara_transaction_types' => '32', 'service_type_name' => 'Monitors Between 5-14 inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 366, 'service_type' => '176', 'avalara_transaction_types' => '32', 'service_type_name' => 'Monitors Between Than 15-34 Inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 367, 'service_type' => '177', 'avalara_transaction_types' => '32', 'service_type_name' => 'Monitors Greater Than 35 Inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 368, 'service_type' => '177', 'avalara_transaction_types' => '32', 'service_type_name' => 'Monitors Greater Than 35 Inches', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 369, 'service_type' => '106', 'avalara_transaction_types' => '34', 'service_type_name' => 'General Rule', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 370, 'service_type' => '230', 'avalara_transaction_types' => '34', 'service_type_name' => 'Coupon Books', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 371, 'service_type' => '232', 'avalara_transaction_types' => '34', 'service_type_name' => 'Non-Lead Based Batteries', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 372, 'service_type' => '574', 'avalara_transaction_types' => '34', 'service_type_name' => 'Fixture', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 373, 'service_type' => '574', 'avalara_transaction_types' => '34', 'service_type_name' => 'Fixture', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 374, 'service_type' => '247', 'avalara_transaction_types' => '36', 'service_type_name' => 'Subscription-Annually-Delivered by US Mail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 376, 'service_type' => '361', 'avalara_transaction_types' => '42', 'service_type_name' => 'Digital Product - Retail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 377, 'service_type' => '362', 'avalara_transaction_types' => '42', 'service_type_name' => 'Digital Product - Subscription', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 378, 'service_type' => '387', 'avalara_transaction_types' => '44', 'service_type_name' => 'Rentals & Leasing', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 379, 'service_type' => '414', 'avalara_transaction_types' => '47', 'service_type_name' => 'Printing Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 380, 'service_type' => '414', 'avalara_transaction_types' => '47', 'service_type_name' => 'Copying Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 375, 'service_type' => '708', 'avalara_transaction_types' => '48', 'service_type_name' => 'Information System Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 381, 'service_type' => '416', 'avalara_transaction_types' => '48', 'service_type_name' => 'Credit Card Processing Fee-Part of Sale', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 382, 'service_type' => '417', 'avalara_transaction_types' => '48', 'service_type_name' => 'Credit Card Processing Fee-Separate Sale', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 383, 'service_type' => '420', 'avalara_transaction_types' => '48', 'service_type_name' => 'Protection & Security Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 384, 'service_type' => '434', 'avalara_transaction_types' => '48', 'service_type_name' => 'Advertising', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 385, 'service_type' => '439', 'avalara_transaction_types' => '48', 'service_type_name' => 'Background Music Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 386, 'service_type' => '447', 'avalara_transaction_types' => '48', 'service_type_name' => 'Telephone Answering Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 387, 'service_type' => '557', 'avalara_transaction_types' => '48', 'service_type_name' => 'Information Systems Services', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 404, 'service_type' => '473', 'avalara_transaction_types' => '50', 'service_type_name' => 'Repair Parts - General Rule', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 388, 'service_type' => '661', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Audio', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 389, 'service_type' => '662', 'avalara_transaction_types' => '57', 'service_type_name' => 'Downloaded Audio', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 390, 'service_type' => '672', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Video - On-Net - Live', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 391, 'service_type' => '673', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Video - On-Net - On Demand', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 392, 'service_type' => '674', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Video - OTT - Live', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 393, 'service_type' => '675', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Video - OTT - On Demand', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 394, 'service_type' => '678', 'avalara_transaction_types' => '57', 'service_type_name' => 'Digital Downloaded Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 395, 'service_type' => '758', 'avalara_transaction_types' => '57', 'service_type_name' => 'Magazines-Retail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 396, 'service_type' => '759', 'avalara_transaction_types' => '57', 'service_type_name' => 'Magazines-Subscription', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 397, 'service_type' => '760', 'avalara_transaction_types' => '57', 'service_type_name' => 'Newspaper-Retail', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 398, 'service_type' => '761', 'avalara_transaction_types' => '57', 'service_type_name' => 'Newspaper-Subscription', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 399, 'service_type' => '763', 'avalara_transaction_types' => '57', 'service_type_name' => 'Internet Download', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 405, 'service_type' => '560', 'avalara_transaction_types' => '57', 'service_type_name' => 'Download from Internet', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 406, 'service_type' => '561', 'avalara_transaction_types' => '57', 'service_type_name' => 'Download to Phone', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 407, 'service_type' => '609', 'avalara_transaction_types' => '57', 'service_type_name' => 'Streaming Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 408, 'service_type' => '633', 'avalara_transaction_types' => '57', 'service_type_name' => 'Downloaded Video', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 400, 'service_type' => '563', 'avalara_transaction_types' => '58', 'service_type_name' => 'Lease-Facilities', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 401, 'service_type' => '564', 'avalara_transaction_types' => '58', 'service_type_name' => 'Lease-Non-Facilities', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 402, 'service_type' => '604', 'avalara_transaction_types' => '58', 'service_type_name' => 'Lease-Facilities-Local Svc', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 403, 'service_type' => '605', 'avalara_transaction_types' => '58', 'service_type_name' => 'Lease-Non-Facilities-Local Svc', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 409, 'service_type' => '10', 'avalara_transaction_types' => '60', 'service_type_name' => 'Usage', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 410, 'service_type' => '585', 'avalara_transaction_types' => '61', 'service_type_name' => 'Interstate MPLS', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 411, 'service_type' => '586', 'avalara_transaction_types' => '61', 'service_type_name' => 'Intrastate MPLS', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 412, 'service_type' => '650', 'avalara_transaction_types' => '61', 'service_type_name' => 'MPLS Intrastate Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 413, 'service_type' => '651', 'avalara_transaction_types' => '61', 'service_type_name' => 'MPLS Install', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 414, 'service_type' => '652', 'avalara_transaction_types' => '61', 'service_type_name' => 'MPLS Service', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 415, 'service_type' => '653', 'avalara_transaction_types' => '61', 'service_type_name' => 'MPLS Interstate Activation', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],

            ['id' => 416, 'service_type' => '577', 'avalara_transaction_types' => '64', 'service_type_name' => 'Enhanced Features', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 417, 'service_type' => '648', 'avalara_transaction_types' => '64', 'service_type_name' => 'Intrastate with FCC Jurisdiction', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 418, 'service_type' => '649', 'avalara_transaction_types' => '64', 'service_type_name' => 'Interstate without FCC Jurisdictions', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 419, 'service_type' => '683', 'avalara_transaction_types' => '64', 'service_type_name' => 'Bridge w Enhanced Feature', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 420, 'service_type' => '684', 'avalara_transaction_types' => '64', 'service_type_name' => 'Interstate Dial in w Enhanced Features', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 421, 'service_type' => '685', 'avalara_transaction_types' => '64', 'service_type_name' => 'Interstate Dial in W Enhanced Features', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],
            ['id' => 422, 'service_type' => '686', 'avalara_transaction_types' => '64', 'service_type_name' => 'Concierge', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 1],

            ['id' => 423, 'service_type' => '710', 'avalara_transaction_types' => '66', 'service_type_name' => 'Service One', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 424, 'service_type' => '711', 'avalara_transaction_types' => '66', 'service_type_name' => 'Service Two', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 425, 'service_type' => '712', 'avalara_transaction_types' => '66', 'service_type_name' => 'Service Three', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 426, 'service_type' => '713', 'avalara_transaction_types' => '66', 'service_type_name' => 'Service Four', 'taxable_amount' => 1, 'lines' => 0, 'minutes' => 0],
            ['id' => 427, 'service_type' => '714', 'avalara_transaction_types' => '66', 'service_type_name' => 'Service Five', 'taxable_amount' => 0, 'lines' => 1, 'minutes' => 0],

        ];
        DB::table('avalara_service_types')->insert($avalara_service_types);
    }
}
