<?php

namespace Crater\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;

/** @mixin \Crater\Models\PbxServices */
class PbxServicesResource extends JsonResource
{
    public function toArray($request): array
    {
        return array_filter([
            'id' => $this->id,
            'creator_id' => $this->creator_id,
            'customer_id' => $this->customer_id,
            'status' => $this->status,
            'apply_tax_type' => $this->apply_tax_type,
            'term' => $this->term,
            'date_begin' => $this->date_begin,
            'allow_discount' => $this->allow_discount,
            'auto_suspension' => $this->auto_suspension,
            'only_callrating' => $this->only_callrating,
            'allow_discount_value' => $this->allow_discount_value,
            'discount_term_type' => $this->discount_term_type,
            'allow_discount_type' => $this->allow_discount_type,
            'date_from' => $this->date_from,
            'date_to' => $this->date_to,
            'time_period' => $this->time_period,
            'time_period_value' => $this->time_period_value,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
            'renewal_date' => $this->renewal_date,
            'pbx_services_number' => $this->pbx_services_number,
            'pbxpackages_price' => $this->pbxpackages_price,
            'discount_val' => $this->discount_val,
            'sub_total' => $this->sub_total,
            'total' => $this->total,
            'tax' => $this->tax,
            'call_rating_preview' => $this->call_rating_preview,
            'inclusive_minutes_seconds_consumed' => $this->inclusive_minutes_seconds_consumed,
            'time_period_type' => $this->time_period_type,
            'date_prev' => $this->date_prev,
            'allow_pbxpackages' => $this->allow_pbxpackages,
            'allow_items' => $this->allow_items,
            'allow_extensions' => $this->allow_extensions,
            'allow_did' => $this->allow_did,
            'allow_aditionalcharges' => $this->allow_aditionalcharges,
            'allow_usagesummary' => $this->allow_usagesummary,
            'cap_extension' => $this->cap_extension,
            'cap_total' => $this->cap_total,
            'is_importing' => $this->is_importing,
            'is_calculating' => $this->is_calculating,
            'total_prorate' => $this->total_prorate,
            'suspension_type' => $this->suspension_type,
            'custom_app_rate_id' => $this->custom_app_rate_id,
            'allow_customapp' => $this->allow_customapp,
            'main_update' => $this->main_update,
            'allow_pbx_packages_update' => $this->allow_pbx_packages_update,
            'first_time_import' => $this->first_time_import,
            'custom_rate_group_items_count' => $this->custom_rate_group_items_count,
            'app_rates_count' => $this->app_rates_count,
            'avalara_exemptions_count' => $this->avalara_exemptions_count,
            'avalara_logs_count' => $this->avalara_logs_count,
            'custom_groups_count' => $this->custom_groups_count,
            'custom_inbound_groups_count' => $this->custom_inbound_groups_count,
            'custom_inbound_items_count' => $this->custom_inbound_items_count,
            'custom_inbound_rates_count' => $this->custom_inbound_rates_count,
            'custom_outbound_groups_count' => $this->custom_outbound_groups_count,
            'custom_outbound_items_count' => $this->custom_outbound_items_count,
            'custom_outbound_rates_count' => $this->custom_outbound_rates_count,
            'formatted_activation_date' => $this->formatted_activation_date,
            'formatted_created_at' => $this->formatted_created_at,
            'formatted_renewal_date' => $this->formatted_renewal_date,
            'international_inbound_rates_count' => $this->international_inbound_rates_count,
            'international_outbound_rates_count' => $this->international_outbound_rates_count,
            'international_rates_count' => $this->international_rates_count,
            'invoices_count' => $this->invoices_count,
            'items_count' => $this->items_count,
            'job_logs_count' => $this->job_logs_count,
            'pbx_cdr_totals_count' => $this->pbx_cdr_totals_count,
            'pbx_cdr_totals_current_count' => $this->pbx_cdr_totals_current_count,
            'pbx_cdr_totals_currentbalance_count' => $this->pbx_cdr_totals_currentbalance_count,
            'pbx_cdr_totals_not_current_count' => $this->pbx_cdr_totals_not_current_count,
            'pbx_extensions_count' => $this->pbx_extensions_count,
            'pbx_service_dids_count' => $this->pbx_service_dids_count,
            'pbx_service_extensions_count' => $this->pbx_service_extensions_count,
            'pbx_service_tax_types_count' => $this->pbx_service_tax_types_count,
            'pbx_service_tax_types_cdrs_count' => $this->pbx_service_tax_types_cdrs_count,
            'pbx_services_app_rate_count' => $this->pbx_services_app_rate_count,
            'pbx_tax_types_history_count' => $this->pbx_tax_types_history_count,
            'schedule_logs_count' => $this->schedule_logs_count,
            'tax_types_cdr_count' => $this->tax_types_cdr_count,
            'taxes_count' => $this->taxes_count,
            'tickets_count' => $this->tickets_count,
            'get_call_detail_register_total_count' => $this->get_call_detail_register_total_count,
            'get_items_count' => $this->get_items_count,
            'getpbx_cdr_totals_count' => $this->getpbx_cdr_totals_count,
            'pbx_cdr_totals_for_invoice_count' => $this->pbx_cdr_totals_for_invoice_count,
            'pbx_custom_cdr_totals_for_invoice_count' => $this->pbx_custom_cdr_totals_for_invoice_count,
            'links' => [
                'self' => route('pbx-server.tenant.services.show', ['service' => $this->id, 'tenant' => $this->pbx_tenant_id]),
            ],
        ]);
    }
}
