<?php
return
    [
    [
        "name"                 => "Calling",
        "descripcion"          => "Avalara Calling",
        "price"                => 0.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 8,
        "status"               => "A",
    ],

    [
        "name"                 => "Lines",
        "descripcion"          => "Avalara Lines",
        "price"                => 5.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 13,
        "status"               => "A",
    ],
    [
        "name"                 => "Pbx",
        "descripcion"          => "Avalara Pbx",
        "price"                => 1.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 14,
        "status"               => "A",
    ],
    [
        "name"                 => "Pbx Extension",
        "descripcion"          => "Avalara Pbx Extension",
        "price"                => 0.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 16,
        "status"               => "A",
    ],
    [
        "name"                 => "Install",
        "descripcion"          => "Avalara Install",
        "price"                => 25.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 2,
        "status"               => "A",
    ],
    [
        "name"                 => "Late Charge",
        "descripcion"          => "Avalara Late Charge",
        "price"                => 3.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 5,
        "status"               => "A",
    ],
    [
        "name"                 => "Enhanced Feature",
        "descripcion"          => "Avalara Enhanced Feature",
        "price"                => 2.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 10,
        "status"               => "A",
    ],
    [
        "name"                 => "PBX Outbound Channel",
        "descripcion"          => "Avalara PBX Outbound Channel",
        "price"                => 1.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 15,
        "status"               => "A",
    ],
    [
        "name"                 => "Equipment Rental",
        "descripcion"          => "Avalara Equipment Rental",
        "price"                => 5.01,
        "avalara_bool"         => true,
        "avalara_type"         => 19,
        "avalara_service_type" => 7,
        "status"               => "A",
    ],
];
